# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf1916e28af209930801a518cd882fedbfee31decf35fd1b339284bc6d0d5f3e0226afcdc3f0560ea958ab3c463e29c8810d64b5eb34e68e3d11303361d50714

test:
  secret_key_base: 20730cb5a90c4d5e75ff5472823f4dcfa1514a70730fe2b9a62a0012ebb31fd86a9b78f3b8343442603296ccbf6d86186ace3324bfb28704ee5dc5d46a7a49d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
